apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push
  namespace: ci
spec:
  description: |
    This pipeline clones a git repo, builds a Docker image with Kaniko and
    pushes it to a registry    
  params:
  - name: repo-url-frontend
    type: string
    description: The git repo URL to clone frontend.
  - name: repo-url-backend
    type: string
    description: The git repo URL to clone backend.
  - name: repo-url-devops
    type: string
    description: The git repo URL to clone backend.
  - name: image-reference
    type: string
  workspaces:
  - name: shared-data-frontend
    description: | 
      This workspace contains the cloned repo files, so they can be read by the
      next task.
  - name: shared-data-backend
    description: | 
      This workspace contains the cloned repo files, so they can be read by the
      next task.
  - name: shared-data-devops
    description: | 
      This workspace contains the cloned repo files, so they can be read by the
      next task.
  - name: git-credentials
    description: My ssh credentials
  tasks:
  - name: fetch-source-frontend
    taskRef:
      name: git-clone-frontend
    workspaces:
    - name: output
      workspace: shared-data-frontend
    - name: ssh-directory
      workspace: git-credentials
    params:
    - name: url
      value: $(params.repo-url-frontend)
  - name: fetch-source-backend
    taskRef:
      name: git-clone-backend
    workspaces:
    - name: output
      workspace: shared-data-backend
    - name: ssh-directory
      workspace: git-credentials
    params:
    - name: url
      value: $(params.repo-url-backend)
  - name: fetch-source-devops
    taskRef:
      name: git-clone-devops
    workspaces:
    - name: output
      workspace: shared-data-devops
    - name: ssh-directory
      workspace: git-credentials
    params:
    - name: url
      value: $(params.repo-url-devops)
  - name: build-push
    runAfter: ["fetch-source-devops", "fetch-source-frontend" , "fetch-source-backend"]
    taskRef:
      name: openshift-build
    workspaces:
    - name: source-frontend
      workspace: shared-data-frontend
    - name: source-backend
      workspace: shared-data-backend
    - name: source-devops
      workspace: shared-data-devops

  